/// <reference path='../typings/node/node.d.ts' />

'use strict';

import * as td from './td';

export var settingsOptionsJson: td.JsonObject =
{
notifications2options: [ "no", "yes" ],
genderoptions: [ "male", "female" ],
yearofbirthoptions: [
2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991,
1990, 1989, 1988, 1987, 1986, 1985, 1984, 1983, 1982, 1981, 1980, 1979,
1978, 1977, 1976, 1975, 1974, 1973, 1972, 1971, 1970, 1969, 1968, 1967,
1966, 1965, 1964, 1963, 1962, 1961, 1960, 1959, 1958, 1957, 1956, 1955,
1954, 1953, 1952, 1951, 1950, 1949, 1948, 1947, 1946, 1945, 1944, 1943,
1942, 1941, 1940, 1939, 1938, 1937, 1936, 1935, 1934, 1933, 1932, 1931,
1930, 1929, 1928, 1927, 1926, 1925, 1924, 1923, 1922, 1921, 1920, 1919,
1918, 1917, 1916, 1915, 1914, 1913, 1912, 1911, 1910, 1909, 1908, 1907,
1906, 1905, 1904, 1903, 1902, 1901, 1900, 1899, 1898, 1897, 1896, 1895
],
cultureoptions: [
"af-ZA", "sq-AL", "gsw-FR", "am-ET", "ar-DZ", "ar-BH", "ar-EG", "ar-IQ",
"ar-JO", "ar-KW", "ar-LB", "ar-LY", "ar-MA", "ar-OM", "ar-QA", "ar-SA",
"ar-SY", "ar-TN", "ar-AE", "ar-YE", "hy-AM", "as-IN", "az-Cyrl-AZ",
"az-Latn-AZ", "ba-RU", "eu-ES", "be-BY", "bn-BD", "bn-IN", "bs-Cyrl-BA",
"bs-Latn-BA", "br-FR", "bg-BG", "ca-ES", "zh-CN", "zh-SG", "zh-HK",
"zh-MO", "zh-TW", "co-FR", "hr-HR", "hr-BA", "cs-CZ", "da-DK",
"prs-AF", "dv-MV", "nl-BE", "nl-NL", "en-AU", "en-BZ", "en-CA",
"en-029", "en-IN", "en-IE", "en-JM", "en-MY", "en-NZ", "en-PH", "en-SG",
"en-ZA", "en-TT", "en-GB", "en-US", "en-ZW", "et-EE", "fo-FO", "fil-PH",
"fi-FI", "fr-BE", "fr-CA", "fr-FR", "fr-LU", "fr-MC", "fr-CH", "fy-NL",
"gl-ES", "ka-GE", "de-AT", "de-DE", "de-LI", "de-LU", "de-CH", "el-GR",
"kl-GL", "gu-IN", "ha-Latn-NG", "he-IL", "hi-IN", "hu-HU", "is-IS",
"ig-NG", "id-ID", "iu-Latn-CA", "iu-Cans-CA", "ga-IE", "xh-ZA", "zu-ZA",
"it-IT", "it-CH", "ja-JP", "kn-IN", "kk-KZ", "km-KH", "qut-GT", "rw-RW",
"sw-KE", "kok-IN", "ko-KR", "ky-KG", "lo-LA", "lv-LV", "lt-LT", "dsb-DE",
"lb-LU", "mk-MK", "ms-BN", "ms-MY", "ml-IN", "mt-MT", "mi-NZ", "arn-CL",
"mr-IN", "moh-CA", "mn-MN", "mn-Mong-CN", "ne-NP", "nb-NO", "nn-NO",
"oc-FR", "or-IN", "ps-AF", "fa-IR", "pl-PL", "pt-BR", "pt-PT", "pa-IN",
"quz-BO", "quz-EC", "quz-PE", "ro-RO", "rm-CH", "ru-RU", "smn-FI",
"smj-NO", "smj-SE", "se-FI", "se-NO", "se-SE", "sms-FI", "sma-NO",
"sma-SE", "sa-IN", "gd-GB", "sr-Cyrl-BA", "sr-Cyrl-ME", "sr-Cyrl-CS",
"sr-Cyrl-RS", "sr-Latn-BA", "sr-Latn-ME", "sr-Latn-CS", "sr-Latn-RS",
"nso-ZA", "tn-ZA", "si-LK", "sk-SK", "sl-SI", "es-AR", "es-VE", "es-BO",
"es-CL", "es-CO", "es-CR", "es-DO", "es-EC", "es-SV", "es-GT", "es-HN",
"es-MX", "es-NI", "es-PA", "es-PY", "es-PE", "es-PR", "es-ES", "es-US",
"es-UY", "sv-FI", "sv-SE", "syr-SY", "tg-Cyrl-TJ", "tzm-Latn-DZ", "ta-IN",
"tt-RU", "te-IN", "th-TH", "bo-CN", "tr-TR", "tk-TM", "uk-UA", "hsb-DE",
"ur-PK", "ug-CN", "uz-Cyrl-UZ", "uz-Latn-UZ", "vi-VN", "cy-GB", "wo-SN",
"sah-RU", "ii-CN", "yo-NG"
],
culturenames: [
"Afrikaans (South Africa)", "Albanian (Albania)", "Alsatian (France)", "Amharic (Ethiopia)", "Arabic (Algeria)", "Arabic (Bahrain)",
"Arabic (Egypt)", "Arabic (Iraq)", "Arabic (Jordan)", "Arabic (Kuwait)", "Arabic (Lebanon)", "Arabic (Libya)", "Arabic (Morocco)",
"Arabic (Oman)", "Arabic (Qatar)", "Arabic (Saudi Arabia)", "Arabic (Syria)", "Arabic (Tunisia)", "Arabic (U.A.E.)", "Arabic (Yemen)",
"Armenian (Armenia)", "Assamese (India)", "Azeri (Cyrillic, Azerbaijan)", "Azeri (Latin, Azerbaijan)", "Bashkir (Russia)",
"Basque (Basque)", "Belarusian (Belarus)", "Bengali (Bangladesh)", "Bengali (India)", "Bosnian (Cyrillic, Bosnia and Herzegovina)",
"Bosnian (Latin, Bosnia and Herzegovina)", "Breton (France)", "Bulgarian (Bulgaria)", "Catalan (Catalan)", "Chinese (Simplified, PRC)",
"Chinese (Simplified, Singapore)", "Chinese (Traditional, Hong Kong S.A.R.)", "Chinese (Traditional, Macao S.A.R.)",
"Chinese (Traditional, Taiwan)", "Corsican (France)", "Croatian (Croatia)", "Croatian (Latin, Bosnia and Herzegovina)",
"Czech (Czech Republic)", "Danish (Denmark)", "Dari (Afghanistan)", "Divehi (Maldives)", "Dutch (Belgium)", "Dutch (Netherlands)",
"English (Australia)", "English (Belize)", "English (Canada)", "English (Caribbean)", "English (India)", "English (Ireland)",
"English (Jamaica)", "English (Malaysia)", "English (New Zealand)", "English (Republic of the Philippines)", "English (Singapore)",
"English (South Africa)", "English (Trinidad and Tobago)", "English (United Kingdom)", "English (United States)",
"English (Zimbabwe)", "Estonian (Estonia)", "Faroese (Faroe Islands)", "Filipino (Philippines)", "Finnish (Finland)",
"French (Belgium)", "French (Canada)", "French (France)", "French (Luxembourg)", "French (Monaco)", "French (Switzerland)", "Frisian (Netherlands)",
"Galician (Galician)", "Georgian (Georgia)", "German (Austria)", "German (Germany)", "German (Liechtenstein)", "German (Luxembourg)", "German (Switzerland)",
"Greek (Greece)", "Greenlandic (Greenland)", "Gujarati (India)", "Hausa (Latin, Nigeria)", "Hebrew (Israel)", "Hindi (India)", "Hungarian (Hungary)",
"Icelandic (Iceland)", "Igbo (Nigeria)", "Indonesian (Indonesia)", "Inuktitut (Latin, Canada)", "Inuktitut (Syllabics, Canada)", "Irish (Ireland)",
"isiXhosa (South Africa)", "isiZulu (South Africa)", "Italian (Italy)", "Italian (Switzerland)", "Japanese (Japan)", "Kannada (India)", "Kazakh (Kazakhstan)",
"Khmer (Cambodia)", "K'iche (Guatemala)", "Kinyarwanda (Rwanda)", "Kiswahili (Kenya)", "Konkani (India)", "Korean (Korea)", "Kyrgyz (Kyrgyzstan)",
"Lao (Lao P.D.R.)", "Latvian (Latvia)", "Lithuanian (Lithuania)", "Lower Sorbian (Germany)", "Luxembourgish (Luxembourg)",
"Macedonian (Former Yugoslav Republic of Macedonia)", "Malay (Brunei Darussalam)", "Malay (Malaysia)", "Malayalam (India)", "Maltese (Malta)",
"Maori (New Zealand)", "Mapudungun (Chile)", "Marathi (India)", "Mohawk (Mohawk)", "Mongolian (Cyrillic, Mongolia)", "Mongolian (Traditional Mongolian, PRC)",
"Nepali (Nepal)", "Norwegian, Bokmål (Norway)", "Norwegian, Nynorsk (Norway)", "Occitan (France)", "Oriya (India)", "Pashto (Afghanistan)",
"Persian", "Polish (Poland)", "Portuguese (Brazil)", "Portuguese (Portugal)", "Punjabi (India)", "Quechua (Bolivia)", "Quechua (Ecuador)",
"Quechua (Peru)", "Romanian (Romania)", "Romansh (Switzerland)", "Russian (Russia)", "Sami, Inari (Finland)", "Sami, Lule (Norway)", "Sami, Lule (Sweden)",
"Sami, Northern (Finland)", "Sami, Northern (Norway)", "Sami, Northern (Sweden)", "Sami, Skolt (Finland)", "Sami, Southern (Norway)",
"Sami, Southern (Sweden)", "Sanskrit (India)", "Scottish Gaelic (United Kingdom)", "Serbian (Cyrillic, Bosnia and Herzegovina)", "Serbian (Cyrillic, Montenegro)",
"Serbian (Cyrillic, Serbia and Montenegro (Former))", "Serbian (Cyrillic, Serbia)", "Serbian (Latin, Bosnia and Herzegovina)", "Serbian (Latin, Montenegro)",
"Serbian (Latin, Serbia and Montenegro (Former))", "Serbian (Latin, Serbia)", "Sesotho sa Leboa (South Africa)", "Setswana (South Africa)",
"Sinhala (Sri Lanka)", "Slovak (Slovakia)", "Slovenian (Slovenia)", "Spanish (Argentina)", "Spanish (Bolivarian Republic of Venezuela)", "Spanish (Bolivia)",
"Spanish (Chile)", "Spanish (Colombia)", "Spanish (Costa Rica)", "Spanish (Dominican Republic)", "Spanish (Ecuador)", "Spanish (El Salvador)",
"Spanish (Guatemala)", "Spanish (Honduras)", "Spanish (Mexico)", "Spanish (Nicaragua)", "Spanish (Panama)", "Spanish (Paraguay)",
"Spanish (Peru)", "Spanish (Puerto Rico)", "Spanish (Spain, International Sort)", "Spanish (United States)", "Spanish (Uruguay)",
"Swedish (Finland)", "Swedish (Sweden)", "Syriac (Syria)", "Tajik (Cyrillic, Tajikistan)", "Tamazight (Latin, Algeria)", "Tamil (India)",
"Tatar (Russia)", "Telugu (India)", "Thai (Thailand)", "Tibetan (PRC)", "Turkish (Turkey)", "Turkmen (Turkmenistan)", "Ukrainian (Ukraine)",
"Upper Sorbian (Germany)", "Urdu (Islamic Republic of Pakistan)", "Uyghur (PRC)", "Uzbek (Cyrillic, Uzbekistan)", "Uzbek (Latin, Uzbekistan)",
"Vietnamese (Vietnam)", "Welsh (United Kingdom)", "Wolof (Senegal)", "Yakut (Russia)", "Yi (PRC)", "Yoruba (Nigeria)" ],
howfoundoptions: [ "friend", "web", "teacher", "other" ],
programmingknowledgeoptions: [ "none", "some", "self-taught", "formal classes" ],
occupationoptions: [ "student", "teacher", "software developer", "other" ],
emailnewsletter2options: [ "no", "yes" ],
emailfrequencyoptions: [ "never", "hourly", "every 4 hours", "daily", "weekly", "monthly" ]
}

