///<reference path='../rt/refs.d.ts'/>
//<reference path='../browser/browser.d.ts'/>
///<reference path='../typings/winjs/winjs.d.ts'/>
///<reference path='../typings/winrt/winrt.d.ts'/>
///<reference path='Senses.ts'/>
///<reference path='Media.ts'/>
///<reference path='Pictures.ts'/>
///<reference path='Picture.ts'/>
///<reference path='Song.ts'/>
///<reference path='Songs.ts'/>
///<reference path='Social.ts'/>
///<reference path='UtilWinRT.ts'/>
///<reference path='ShareManager.ts'/>
///<reference path='Web.ts'/>
///<reference path='Phone.ts'/>
///<reference path='Camera.ts'/>
///<reference path='Languages.ts'/>
///<reference path='PrintManager.ts'/>
///<reference path='BingMaps.ts'/>
///<reference path='MediaManager.ts'/>
///<reference path='AdManager.ts'/>
///<reference path='PageButtonManager.ts'/>
///<reference path='Tiles.ts' />
///<reference path='Bazaar.ts' />
