///<reference path='../rt/refs.d.ts'/>
///<reference path='../rt/typings.d.ts'/>
//<reference path='../browser/browser.d.ts'/>
///<reference path='runtime.ts'/>
///<reference path='Social.ts'/>
///<reference path='DeviceMotion.ts'/>
///<reference path='DeviceOrientation.ts'/>
///<reference path='Web.ts'/>
///<reference path='Player.ts'/>
///<reference path='Senses.ts'/>
///<reference path='Languages.ts'/>
///<reference path='ShareManager.ts'/>
///<reference path='ScreenshotManager.ts'/>
///<reference path='Media.ts'/>
///<reference path='Sound.ts'/>
///<reference path='Tags.ts'/>
///<reference path='Tiles.ts' />
///<reference path='ArtCache.ts'/>
///<reference path='BluetoothDevice.ts'/>
///<reference path='Radio.ts'/>
///<reference path='AdManager.ts'/>
///<reference path='Bazaar.ts' />
